// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1a6kc_M4PPbWRbG0mkBJx6Ucf3026BfI',
    appId: '1:51899569832:web:7c9eaa8e61a7c3f696d49d',
    messagingSenderId: '51899569832',
    projectId: 'stellar-chat-db371',
    authDomain: 'stellar-chat-db371.firebaseapp.com',
    storageBucket: 'stellar-chat-db371.appspot.com',
    measurementId: 'G-8TF1NL2DW4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkyaWoW_OZAICqApd7iWpHtaOYUqPnfJ0',
    appId: '1:51899569832:android:a9df53c4d762094a96d49d',
    messagingSenderId: '51899569832',
    projectId: 'stellar-chat-db371',
    storageBucket: 'stellar-chat-db371.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBukYTwB9VUflO1LBNGSVbHiV4taUfBCe0',
    appId: '1:51899569832:ios:8fd5af47003625ca96d49d',
    messagingSenderId: '51899569832',
    projectId: 'stellar-chat-db371',
    storageBucket: 'stellar-chat-db371.appspot.com',
    iosBundleId: 'com.example.baseProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBukYTwB9VUflO1LBNGSVbHiV4taUfBCe0',
    appId: '1:51899569832:ios:8fd5af47003625ca96d49d',
    messagingSenderId: '51899569832',
    projectId: 'stellar-chat-db371',
    storageBucket: 'stellar-chat-db371.appspot.com',
    iosBundleId: 'com.example.baseProject',
  );
}
